[package]
name = "euler"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
num = "*"
rand = "*"
euler_00 = { path = "euler_00/" }
euler_01 = { path = "euler_01/" }
euler_02 = { path = "euler_02/" }
euler_03 = { path = "euler_03/" }
