//! [2] Even Fibonacci numbers
//! --------------------------
//!
//! ### Problem
//! ```
//! Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//!     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//! By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//! ```
extern crate num;
use self::num::integer::Integer;
use utils;
use utils::Sum;

pub fn solve() -> usize {
    let limit = 4_000_000;
    utils::fibonacci::<usize>().take_while(|&n| n <= limit).filter(|n| n.is_even()).summation()
}
